webtalk_init -webtalk_dir C:/project/FPGA/xsim.dir/tb_fpga_top_arty_a7_uart_snapshot/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 18 16:57:11 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6ce132ec-9a6b-4dd3-9a70-8af80991e102" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a4afa10d-5eb6-4692-aa36-1657e276aa49" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-1240P" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "18" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "off" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "673 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "64 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1766" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "503" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "135796_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3814941905 -regid "" -xml C:/project/FPGA/xsim.dir/tb_fpga_top_arty_a7_uart_snapshot/webtalk/usage_statistics_ext_xsim.xml -html C:/project/FPGA/xsim.dir/tb_fpga_top_arty_a7_uart_snapshot/webtalk/usage_statistics_ext_xsim.html -wdm C:/project/FPGA/xsim.dir/tb_fpga_top_arty_a7_uart_snapshot/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
